<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <AssemblyName>UOTinker</AssemblyName>
    <RootNamespace>UOTinker</RootNamespace>
    <Version>0.2.0</Version>
    <Product>UOTinker</Product>
    <ApplicationIcon>Setup\Icons\UOTinker.ico</ApplicationIcon>
    <Copyright>GPL v3 or later - Daniel Kowarek</Copyright>
  </PropertyGroup>

</Project>
