namespace UOTinker;

public static class LocEn3
{
    public static readonly (string de, string en)[] Pairs =
    {
        ("UO Tinker Version {0} - F1 für Hilfe", "UO Tinker Version {0} - F1 for help"),
        ("Ordner wählen", "Choose folder"),
        ("Neu laden", "Reload"),
        ("Hilfe (F1)", "Help (F1)"),
        ("Über UOTinker", "About UOTinker"),
        ("UOTinker unterstützen (Ko-fi)", "Support UOTinker (Ko-fi)"),
        ("Beenden", "Exit"),
        ("Datenordner wählen ...", "Choose data folder ..."),
        ("Sphere-Skriptordner wählen (optional) ...", "Choose Sphere script folder (optional) ..."),
        ("Sphere-Skriptordner nicht verwenden", "Do not use Sphere script folder"),
        ("Schreibschutz (nichts ändern)", "Read-only mode (change nothing)"),
        ("Schreibschutz aktiv: Es wird nichts geändert.", "Read-only mode on: nothing will be changed."),
        ("Schreibschutz aus: Änderungen können gespeichert werden (mit Sicherung).", "Read-only mode off: changes can be saved (with backup)."),
        ("Jetzt nach Updates suchen", "Check for updates now"),
        ("Beim Start nach Updates suchen", "Check for updates on startup"),
        ("Die Update-Prüfung ist fehlgeschlagen: {0}", "The update check failed: {0}"),
        ("UOTinker {0} ist aktuell.", "UOTinker {0} is up to date."),
        ("Neue Version {0} verfügbar (Übersicht: Jetzt aktualisieren).", "New version {0} available (Overview: Update now)."),
        ("UOTinker {0} laden und installieren?\nDas Programm wird dazu beendet.", "Download and install UOTinker {0}?\nThe program will close for this."),
        ("Update wird geladen ... {0} %", "Downloading update ... {0} %"),
        ("Das Update ist fehlgeschlagen: {0}", "The update failed: {0}"),
        ("{0} ungespeicherte Änderung(en) gehen verloren. Trotzdem fortfahren?", "{0} unsaved change(s) will be lost. Continue anyway?"),
        ("Ordner mit den Ultima-Online-Dateien wählen (art.mul, tiledata.mul, hues.mul ...)", "Choose the folder with the Ultima Online files (art.mul, tiledata.mul, hues.mul ...)"),
        ("Kein Datenordner gewählt. Zahnrad unten links: Datenordner wählen.", "No data folder chosen. Gear icon at the bottom left: Choose data folder."),
        ("Lade {0} ...", "Loading {0} ..."),
        ("Fehler beim Laden: {0}", "Error while loading: {0}"),
        ("   |   Sphere-Skripte: {0} Dateien", "   |   Sphere scripts: {0} files"),
        ("Datenordner: {0}{1}   |   Tiledata: {2}   |   UOP-Einträge: {3}", "Data folder: {0}{1}   |   Tiledata: {2}   |   UOP entries: {3}"),
        ("ok", "ok"),
        ("NICHT geladen", "NOT loaded"),
        ("ÜBERSICHT", "OVERVIEW"),
        ("Übersicht", "Overview"),
        ("GRAFIK", "GRAPHICS"),
        ("Items (Art)", "Items (Art)"),
        ("Alle Item-Grafiken aus art.mul bis zur höchsten ID, auch freie Slots.", "All item graphics from art.mul up to the highest ID, including free slots."),
        ("Landtiles", "Land tiles"),
        ("Bodenkacheln (Index 0 bis 0x3FFF in art.mul).", "Ground tiles (index 0 to 0x3FFF in art.mul)."),
        ("Alle Gumps aus gumpart.mul bis zur höchsten ID, auch freie Slots.", "All gumps from gumpart.mul up to the highest ID, including free slots."),
        ("Radarfarben je Land- und Item-Grafik (radarcol.mul).", "Radar colors per land and item graphic (radarcol.mul)."),
        ("Alle Farben aus hues.mul mit je 32 Farbwerten.", "All colors from hues.mul with 32 color values each."),
        ("ANIMATIONEN", "ANIMATIONS"),
        ("Alle Bodies mit Quellen aus anim.mul bis anim6.mul, bodyconv.def, body.def und UOP.", "All bodies with sources from anim.mul to anim6.mul, bodyconv.def, body.def and UOP."),
        ("Item-AnimIDs", "Item AnimIDs"),
        ("Animations-IDs, die Items in der Tiledata benutzen, mit Paperdoll-Gumps.", "Animation IDs used by items in the tiledata, with paperdoll gumps."),
        ("Rohdateien", "Raw files"),
        ("Jede Animationsdatei einzeln, ohne body.def und bodyconv.def.", "Each animation file on its own, without body.def and bodyconv.def."),
        ("DATEN", "DATA"),
        ("Name, Flags und Eigenschaften aller Land- und Item-Kacheln.", "Name, flags and properties of all land and item tiles."),
        ("Alle ITEMDEFs der Sphere-Skripte mit Item-ID, Tiledata-Name und Problemen.", "All ITEMDEFs from the Sphere scripts with item ID, tiledata name and problems."),
        ("Skill-Tabelle (skills.idx/skills.mul).", "Skill table (skills.idx/skills.mul)."),
        ("Clientsprache: Textnummern und Texte je Sprache.", "Client language: text numbers and texts per language."),
        ("Fehler: {0}", "Error: {0}"),
        ("UO Tinker - Betrachter und Editor für die Dateien deines Ultima-Online-Clients", "UO Tinker - viewer and editor for the files of your Ultima Online client"),
        ("Datenordner wählen", "Choose data folder"),
        ("Guten Morgen", "Good morning"),
        ("Guten Tag", "Good afternoon"),
        ("Guten Abend", "Good evening"),
        ("ITEM-ART", "ITEM ART"),
        ("belegt von {0:N0} Slots, {1:N0} frei", "used of {0:N0} slots, {1:N0} free"),
        ("Bodies mit Animation, davon {0:N0} nur in UOP", "Bodies with animation, {0:N0} of them only in UOP"),
        ("OHNE ANIMATION", "NO ANIMATION"),
        ("Chardefs ohne Animationsdaten", "Chardefs without animation data"),
        ("ITEMS MIT LÜCKEN", "ITEMS WITH GAPS"),
        ("{0:N0} ohne Tiledata, {1:N0} ohne Art, {2:N0} Anim (Klick)", "{0:N0} without tiledata, {1:N0} without art, {2:N0} anim (click)"),
        ("SPHERE-KATALOG", "SPHERE CATALOG"),
        ("Body-Nummern mit CHARDEF, {0:N0} mit ITEMDEF", "Body numbers with CHARDEF, {0:N0} with ITEMDEF"),
        ("Datei", "File"),
        ("Größe", "Size"),
        ("Inhalt", "Contents"),
        ("fehlt", "missing"),
        ("Dateien im Datenordner", "Files in the data folder"),
        ("Zuletzt angesehen", "Recently viewed"),
        ("{0}   ·   {1}", "{0}   ·   {1}"),
        ("Doppelklick öffnet den Eintrag erneut.", "Double-click opens the entry again."),
        ("Schnellaktionen", "Quick actions"),
        ("Tiledata: {0} ({1:N0})", "Tiledata: {0} ({1:N0})"),
        ("Chardefs ohne Animation anzeigen (Bodies)", "Show chardefs without animation (Bodies)"),
        ("Nur UOP-Animationen anzeigen (Bodies)", "Show UOP-only animations (Bodies)"),
        ("Bodies ohne Chardef anzeigen (Animation vorhanden)", "Show bodies without chardef (animation present)"),
        ("Item-AnimIDs ohne Animation", "Item AnimIDs without animation"),
        ("Freie Item-Art-Slots", "Free item art slots"),
        ("Freie Gump-Slots", "Free gump slots"),
        ("Leere Hues", "Empty hues"),
        ("Doppelklick führt aus.", "Double-click runs the action."),
        ("Jetzt aktualisieren", "Update now"),
        ("Neue Version {0} verfügbar (installiert: {1})", "New version {0} available (installed: {1})"),
        ("{0:N0} Index-Einträge (Land + Items)", "{0:N0} index entries (land + items)"),
        ("{0:N0} Gump-Slots", "{0:N0} gump slots"),
        ("{0:N0} Land + {1:N0} Items", "{0:N0} land + {1:N0} items"),
        ("{0:N0} Hues", "{0:N0} hues"),
        ("Radarfarben", "Radar colors"),
        ("{0} Skills", "{0} skills"),
        ("bis Body/Index {0}", "up to body/index {0}"),
        ("UOP-Animation", "UOP animation"),
        ("{0} Einträge", "{0} entries"),
        ("Typ", "Type"),
        ("Problem", "Problem"),
        ("Status", "Status"),
        ("Quelle", "Source"),
        ("Chardef", "Chardef"),
        ("Eintrag", "Entry"),
        ("Dieses Programm ist freie Software: Sie können es unter den Bedingungen der GNU General Public License, wie von der Free Software Foundation veröffentlicht, weitergeben und/oder ändern, entweder gemäß Version 3 der Lizenz oder (nach Ihrer Wahl) jeder späteren Version.", "This program is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version."),
        ("Dieses Programm wird in der Hoffnung verbreitet, dass es nützlich ist, aber OHNE JEDE GEWÄHRLEISTUNG; sogar ohne die implizite Gewährleistung der MARKTFÄHIGKEIT oder EIGNUNG FÜR EINEN BESTIMMTEN ZWECK. Details finden Sie in der GNU General Public License.", "This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details."),
        ("Sie sollten eine Kopie der GNU General Public License zusammen mit diesem Programm erhalten haben. Falls nicht, siehe <https://www.gnu.org/licenses/>. Enthält Code von ClassicUO unter der BSD-2-Clause-Lizenz (siehe THIRD-PARTY-NOTICES.md).", "You should have received a copy of the GNU General Public License along with this program. If not, see <https://www.gnu.org/licenses/>. Contains code from ClassicUO under the BSD 2-Clause License (see THIRD-PARTY-NOTICES.md)."),
        ("© {0} {1}\r\nErstellt am {2}\r\n\r\nBetrachter und Editor für die Dateien eines Ultima-Online-Clients (Tiledata, Art, Land, Gumps und mehr). Für alle Shards gedacht.", "© {0} {1}\r\nBuilt on {2}\r\n\r\nViewer and editor for the files of an Ultima Online client (tiledata, art, land, gumps and more). Made for all shards."),
        ("Das Release enthält keine Prüfsumme; das Update wird nicht geladen.", "The release contains no checksum; the update will not be downloaded."),
        ("Die Prüfsumme der geladenen Datei stimmt nicht mit der des Releases überein. Das Update wurde verworfen.", "The checksum of the downloaded file does not match the release. The update was discarded."),
        ("Der Schreibschutz ist aktiv (Zahnrad unten links: Schreibschutz ausschalten).", "Read-only mode is on (gear icon at the bottom left: turn off read-only mode)."),
        ("radarcol.mul fehlt.", "radarcol.mul is missing."),
        ("hues.mul fehlt.", "hues.mul is missing."),
        ("skills.idx fehlt.", "skills.idx is missing."),
        ("{0} und {1}", "{0} and {1}"),
        ("Diese Datei ist BWT-komprimiert. Komprimierte Cliloc-Dateien kann UOTinker nicht schreiben.", "This file is BWT-compressed. UOTinker cannot write compressed cliloc files."),
        ("Die Datei konnte nicht gelesen werden.", "The file could not be read."),
    };
}
