namespace UOTinker;

public static class LocEn1
{
    public static readonly (string de, string en)[] Pairs =
    {
        ("Hinweis", "Note"),
        ("UO Tinker - Hilfe", "UO Tinker - Help"),
        ("Willkommen", "Welcome"),
        ("<p>UO Tinker zeigt die Dateien eines Ultima-Online-Clients an und pflegt Tiledata, Item-Art, Landtiles und Gumps. Du wählst einen beliebigen Ordner mit den Client-Dateien (art.mul, tiledata.mul, hues.mul ...) als Datenordner; angezeigt werden Items, Gumps, Tiledata, Landtiles, Radarcolor, Hues, Animationen, Skills und Cliloc, jeweils bis zur höchsten ID, auch freie Slots. Optional lässt sich zusätzlich der Skriptordner eines Sphere-Servers angeben, damit Items mit ihren ITEMDEFs abgeglichen werden.</p>",
            "<p>UO Tinker displays the files of an Ultima Online client and maintains Tiledata, item Art, Landtiles and Gumps. You pick any folder containing the client files (art.mul, tiledata.mul, hues.mul ...) as the data folder; items, Gumps, Tiledata, Landtiles, Radarcolor, Hues, animations, skills and Cliloc are shown up to the highest ID, including free slots. Optionally you can also specify the script folder of a Sphere server so that items are matched against their ITEMDEFs.</p>"),
        ("<p>Links in der Seitenleiste wählst du den Bereich. Die meisten Bereiche haben oben eine Suche, Filter und die Umschaltung zwischen Raster und Liste. Rechts steht die Vorschau des gewählten Eintrags.</p>",
            "<p>Choose the section in the sidebar on the left. Most sections have a search box, filters and a switch between grid and list at the top. The preview of the selected entry is on the right.</p>"),
        ("Ändern lassen sich Tiledata, Item-Art, Landtiles und Gumps. Vor jedem Schreiben wird eine Sicherung angelegt. Arbeite trotzdem am besten an einer Kopie deines Client-Ordners. Wer nur ansehen will, schaltet im Zahnrad-Menü unten links den Schreibschutz ein. Alles andere ist lesend.",
            "Tiledata, item Art, Landtiles and Gumps can be edited. A backup is created before every write. Still, it is best to work on a copy of your client folder. If you only want to look, turn on write protection in the gear menu at the bottom left. Everything else is read-only."),
        ("<p>Weiter mit {0}, {1} oder {2}.</p>", "<p>Continue with {0}, {1} or {2}.</p>"),
        ("Bedienung", "Usage"),
        ("Tiledata", "Tiledata"),
        ("Tiledata bearbeiten", "Editing Tiledata"),
        ("Über UOTinker", "About UOTinker"),
        ("<p>Betrachter und Editor für die Dateien eines Ultima-Online-Clients. Das Programm ist frei und nicht an einen bestimmten Shard gebunden. Das Fenster 'Über UOTinker' (Symbol ⓘ unten links) zeigt Version, Erstelldatum und Lizenz.</p>",
            "<p>Viewer and editor for the files of an Ultima Online client. The program is free and not tied to any particular shard. The 'About UOTinker' window (ⓘ icon at the bottom left) shows the version, build date and license.</p>"),
        ("Lizenz", "License"),
        ("Unterstützen", "Support"),
        ("Wenn dir UOTinker nützt, kannst du die Entwicklung freiwillig auf Ko-fi unterstützen (Herz-Symbol unten links). Das Programm bleibt kostenlos und frei.",
            "If UOTinker is useful to you, you can support its development voluntarily on Ko-fi (heart icon at the bottom left). The program stays free of charge and open."),
        ("Suche", "Search"),
        ("Mehrere Wörter, alle müssen vorkommen. Gesucht wird in ID (dezimal und hex, z. B. 0xf60), Namen, Sphere-Defnames und Problemtext.",
            "Several words; all of them must match. The search covers ID (decimal and hex, e.g. 0xf60), names, Sphere defnames and problem text."),
        ("Filter", "Filters"),
        ("Die Auswahlfelder neben der Suche. Sie wirken zusammen mit der Suche (UND). Bei Tiledata gibt es zum Beispiel Problem, Flag, Art und Sphere.",
            "The drop-downs next to the search box. They combine with the search (AND). For Tiledata there are, for example, Problem, Flag, Art and Sphere."),
        ("Raster und Liste", "Grid and list"),
        ("Oben rechts schaltest du zwischen Thumbnail-Raster und Liste um. Im Raster stellt Zelle die Größe ein; Pfeiltasten, Bild auf/ab, Pos1/Ende und Mausrad bewegen die Auswahl.",
            "At the top right you switch between thumbnail grid and list. In the grid, Cell sets the size; arrow keys, Page Up/Down, Home/End and the mouse wheel move the selection."),
        ("CSV exportieren", "Export CSV"),
        ("Der Knopf oben rechts speichert die aktuell angezeigte Liste (also mit Suche und Filtern) als CSV-Datei: Semikolon als Trenner, UTF-8 mit Kennung, damit Excel Umlaute richtig liest. Die Spalten entsprechen der Liste; bei der Tiledata ist auch die Problem-Spalte dabei.",
            "The button at the top right saves the currently shown list (including search and filters) as a CSV file: semicolon separated, UTF-8 with BOM so that Excel reads umlauts correctly. The columns match the list; for Tiledata the Problem column is included."),
        ("Gehe zu ID", "Go to ID"),
        ("ID eingeben (dezimal oder 0x hex) und Enter. Der Eintrag muss in der aktuellen Auswahl liegen, sonst Filter zurücksetzen.",
            "Enter an ID (decimal or 0x hex) and press Enter. The entry must be within the current selection; otherwise reset the filters."),
        ("Updates", "Updates"),
        ("Beim Start fragt UOTinker bei GitHub nach der neuesten Version (abschaltbar im Zahnrad-Menü; dort auch 'Jetzt nach Updates suchen'). Gibt es eine neuere Version, erscheint auf der Übersicht oben eine Zeile mit 'Jetzt aktualisieren'. Das Programm lädt dann den Installer, vergleicht seine SHA-256-Prüfsumme mit der des Releases, startet ihn und beendet sich. Stimmt die Prüfsumme nicht, wird nichts installiert. Einstellungen und Sicherungen bleiben erhalten.",
            "On startup UOTinker asks GitHub for the latest version (can be turned off in the gear menu, which also has 'Check for updates now'). If a newer version exists, a line with 'Update now' appears at the top of the overview. The program then downloads the installer, compares its SHA-256 checksum with the one of the release, starts it and exits. If the checksum does not match, nothing is installed. Settings and backups are kept."),
        ("Datenordner", "Data folder"),
        ("Zahnrad unten links: Datenordner wählen, optional einen Sphere-Skriptordner angeben und den Schreibschutz umschalten. Beim ersten Start fragt das Programm nach dem Datenordner. Neu laden (Pfeil) liest alles erneut ein.",
            "Gear at the bottom left: choose the data folder, optionally specify a Sphere script folder and toggle write protection. On first start the program asks for the data folder. Reload (arrow) reads everything again."),
        ("Zuletzt angesehen", "Recently viewed"),
        ("Auf der Übersicht stehen die zuletzt geöffneten Einträge; Doppelklick springt wieder hin.",
            "The overview lists the most recently opened entries; double-click jumps back to one."),
        ("Items mit Lücken", "Items with gaps"),
        ("Die rote Karte auf der Übersicht zählt Items mit mindestens einem Tiledata-Problem (Art ohne Tiledata, Tiledata ohne Art, Animations- und Layer-Probleme, ITEMDEF ohne Namen). Ein Klick öffnet die Tiledata-Liste mit dem Filter 'Irgendein Problem'. In den Schnellaktionen steht jede Problemart einzeln mit ihrer Anzahl; Doppelklick öffnet die gefilterte Liste. Die Zahlen aktualisieren sich nach Änderungen, sobald du zur Übersicht zurückkehrst.",
            "The red card on the overview counts items with at least one Tiledata problem (Art without Tiledata, Tiledata without Art, animation and layer problems, ITEMDEF without name). A click opens the Tiledata list with the filter 'Any problem'. The quick actions list each problem type separately with its count; double-click opens the filtered list. The numbers update after changes as soon as you return to the overview."),
        ("Freie Slots sind grau markiert. 'Frei' heißt: kein Inhalt in der Datei, nicht unbedingt ungenutzt im Spiel.",
            "Free slots are marked gray. 'Free' means: no content in the file, not necessarily unused in the game."),
        ("Bereiche", "Sections"),
        ("<p>Jeder Bereich in der Seitenleiste hat eine eigene Seite:</p>", "<p>Each section in the sidebar has its own page:</p>"),
        ("Items (Art)", "Items (Art)"),
        ("Landtiles", "Land tiles"),
        ("Gumps", "Gumps"),
        ("Radarcolor", "Radarcolor"),
        ("Hues", "Hues"),
        ("Bodies / Monster", "Bodies / Monsters"),
        ("Item-AnimIDs", "Item AnimIDs"),
        ("Rohdateien", "Raw files"),
        ("Sphere-ITEMDEF", "Sphere ITEMDEF"),
        ("Skills", "Skills"),
        ("Cliloc", "Cliloc"),
        ("<p>Alle Item-Grafiken aus art.mul bis zur höchsten Tiledata-ID.</p>", "<p>All item graphics from art.mul up to the highest Tiledata ID.</p>"),
        ("Status", "Status"),
        ("Belegt, frei oder außerhalb. Frei heißt: kein Bild in art.mul.", "Used, free or out of range. Free means: no image in art.mul."),
        ("Tiledata-Name", "Tiledata name"),
        ("Name aus der Tiledata. Ist er leer, fehlt die Pflege.", "Name from the Tiledata. If it is empty, the entry has not been maintained."),
        ("Nur mit angegebenem Sphere-Skriptordner: zeigt die Definitionen, die diese ID benutzen.",
            "Only with a Sphere script folder specified: shows the definitions that use this ID."),
        ("AnimID", "AnimID"),
        ("Animations-ID aus der Tiledata, falls das Item am Körper getragen wird.", "Animation ID from the Tiledata, if the item is worn on the body."),
        ("<p>Bearbeiten: siehe {0}.</p>", "<p>Editing: see {0}.</p>"),
        ("Item-Art bearbeiten", "Editing item Art"),
        ("<p>Rechts neben der Liste steht ein Formular zum gewählten Slot. Änderungen sammeln sich im Programm und werden erst mit 'Art speichern' in die Dateien geschrieben.</p>",
            "<p>To the right of the list is a form for the selected slot. Changes accumulate in the program and are only written to the files with 'Save Art'.</p>"),
        ("Aus Bild importieren", "Import from image"),
        ("Wählt ein Bild (PNG, BMP, GIF oder JPG) und wandelt es in das Item-Format um. Pixel mit weniger als 50 % Deckkraft werden transparent, die Farben werden auf 15 Bit reduziert (reines Schwarz wird zu einem sehr dunklen Grau, weil Schwarz im Format 'durchsichtig' heißt). Größe 1 bis 1024 Pixel je Seite; die Bildgröße bestimmt die Item-Größe im Spiel.",
            "Picks an image (PNG, BMP, GIF or JPG) and converts it to the item format. Pixels with less than 50 % opacity become transparent, and colors are reduced to 15 bits (pure black becomes a very dark gray, because black means 'transparent' in the format). Size 1 to 1024 pixels per side; the image size determines the item size in the game."),
        ("Als PNG exportieren", "Export as PNG"),
        ("Speichert die aktuelle Grafik des Slots als PNG, auch bei noch nicht gespeicherten Änderungen.",
            "Saves the slot's current graphic as PNG, even if the changes are not saved yet."),
        ("Slot leeren", "Clear slot"),
        ("Entfernt die Grafik beim Speichern. Nach Rückfrage.", "Removes the graphic when saving. Asks for confirmation."),
        ("Eintrag zurücksetzen / Alle verwerfen", "Reset entry / Discard all"),
        ("Nimmt die ungespeicherte Änderung dieses Slots bzw. aller Slots zurück.", "Reverts the unsaved change of this slot or of all slots."),
        ("Art speichern", "Save Art"),
        ("Hängt die neuen Grafiken hinten an art.mul an und trägt sie in artidx.mul ein. Bereits vorhandene Daten in art.mul werden nicht verändert; ersetzte oder entfernte Grafiken bleiben als ungenutzter Platz in der Datei. Vor dem Schreiben wird artidx.mul unter %APPDATA%\\UOTinker\\backups gesichert, dazu eine Textdatei mit der ursprünglichen Größe von art.mul.",
            "Appends the new graphics to the end of art.mul and records them in artidx.mul. Existing data in art.mul is not changed; replaced or removed graphics remain as unused space in the file. Before writing, artidx.mul is backed up to %APPDATA%\\UOTinker\\backups, along with a text file containing the original size of art.mul."),
        ("Nicht bei aktivem Schreibschutz. art.mul, artidx.mul und tiledata.mul gehören zusammen: wer die Dateien weitergibt (Client, Spieler, Server), gibt alle drei gemeinsam weiter. Server lesen die Grafikdatei oft nicht, aber meist die Tiledata.",
            "Not available while write protection is on. art.mul, artidx.mul and tiledata.mul belong together: whoever distributes the files (client, players, server) should distribute all three together. Servers often do not read the graphics file, but usually read the Tiledata."),
        ("Land-Kacheln", "Land tiles"),
        ("Im Tab Landtiles gilt dasselbe. Das Bild muss genau 44 x 44 Pixel groß sein; gespeichert wird nur die Raute in der Mitte (1012 Pixel), die Ecken werden ignoriert. Land hat keine Transparenz, Schwarz bleibt Schwarz. Gespeichert wird wie bei Items in art.mul und artidx.mul.",
            "The same applies in the Landtiles tab. The image must be exactly 44 x 44 pixels; only the diamond in the middle (1012 pixels) is saved, the corners are ignored. Land has no transparency, black stays black. As with items, it is saved to art.mul and artidx.mul."),
        ("Gumps", "Gumps"),
        ("Im Tab Gumps gilt dasselbe mit Bildern von 1 bis 2048 Pixeln je Seite. Pixel mit weniger als 50 % Deckkraft werden transparent. Gespeichert wird in gumpart.mul und gumpidx.mul; die Sicherung betrifft gumpidx.mul. Paperdoll-Gumps liegen bei 50000 + AnimID (männlich) und 60000 + AnimID (weiblich) und sind in der Praxis 260 x 237 Pixel groß.",
            "The same applies in the Gumps tab, with images of 1 to 2048 pixels per side. Pixels with less than 50 % opacity become transparent. It is saved to gumpart.mul and gumpidx.mul; the backup covers gumpidx.mul. Paperdoll Gumps are at 50000 + AnimID (male) and 60000 + AnimID (female) and are 260 x 237 pixels in practice."),
        ("Das Programm sollte nicht laufen, während der Spielclient die Dateien geöffnet hat; dann meldet es einen Fehler und ändert nichts. Art-Änderungen und Gump-Änderungen werden getrennt gespeichert (Art und Land zusammen, Gumps für sich).",
            "The program should not run while the game client has the files open; it then reports an error and changes nothing. Art changes and Gump changes are saved separately (Art and Land together, Gumps on their own)."),
        ("<p>Bodenkacheln (Index 0 bis 0x3FFF). Zu jeder Kachel stehen Name, TexID und Flags aus der Tiledata.",
            "<p>Ground tiles (index 0 to 0x3FFF). For each tile, the name, TexID and flags from the Tiledata are shown."),
        ("<p>Alle Gumps aus gumpart.mul bis zur höchsten ID.</p>", "<p>All Gumps from gumpart.mul up to the highest ID.</p>"),
        ("Bedeutung", "Meaning"),
        ("Ab 50000 sind es männliche, ab 60000 weibliche Paperdoll-Gumps; die AnimID ist die ID minus 50000 bzw. 60000.",
            "From 50000 they are male, from 60000 female Paperdoll Gumps; the AnimID is the ID minus 50000 or 60000."),
        ("<p>Radarfarbe je Land- und Item-Grafik (radarcol.mul), ein 16-Bit-Wert pro Art-Index. Rechts neben der Liste steht ein Formular zum gewählten Eintrag.</p>",
            "<p>Radar color for each land and item graphic (radarcol.mul), one 16-bit value per Art index. To the right of the list is a form for the selected entry.</p>"),
        ("Farbe", "Color"),
        ("Der Wert als 15-Bit-Hexzahl (Rot, Grün und Blau je 5 Bit). Das Farbfeld daneben zeigt das Ergebnis; 'Farbe wählen' öffnet den Farbdialog.",
            "The value as a 15-bit hex number (red, green and blue with 5 bits each). The color swatch next to it shows the result; 'Choose color' opens the color dialog."),
        ("Aus der Grafik berechnen", "Calculate from graphic"),
        ("Setzt den Mittelwert aller nicht transparenten Pixel der Grafik.", "Sets the average of all non-transparent pixels of the graphic."),
        ("Fehlende Item-Farben füllen", "Fill missing item colors"),
        ("Berechnet die Farbe für alle Items, die eine Grafik, aber die Radarfarbe 0 haben, und merkt sie als Änderung vor.",
            "Calculates the color for all items that have a graphic but radar color 0, and queues it as a change."),
        ("Speichern", "Save"),
        ("Schreibt alle geänderten Einträge dieser Datei. Zuvor wird die vorherige Datei unter %APPDATA%\\UOTinker\\backups gesichert. Die Zahl in Klammern ist die Menge der geänderten Einträge. Bei aktivem Schreibschutz ist der Knopf gesperrt.",
            "Writes all changed entries of this file. Beforehand, the previous file is backed up to %APPDATA%\\UOTinker\\backups. The number in parentheses is the count of changed entries. The button is disabled while write protection is on."),
        ("Stellt den Eintrag oder alle ungespeicherten Änderungen auf den Stand der Datei zurück.",
            "Restores the entry or all unsaved changes to the state of the file."),
        ("<p>Alle Farben aus hues.mul mit je 32 Farbwerten. Das Raster zeigt die Farbverläufe. Rechts neben der Liste steht ein Formular zum gewählten Hue.</p>",
            "<p>All colors from hues.mul with 32 color values each. The grid shows the color gradients. To the right of the list is a form for the selected Hue.</p>"),
        ("Name", "Name"),
        ("Höchstens 19 Zeichen, Latin-1.", "At most 19 characters, Latin-1."),
        ("Tabelle von / bis", "Table from / to"),
        ("Die beiden Tabellenwerte des Eintrags, bleiben meist unverändert.", "The two table values of the entry; they usually stay unchanged."),
        ("Farbfelder", "Color swatches"),
        ("Ein Klick auf eines der 32 Felder öffnet den Farbdialog. Die Farben werden auf 15 Bit reduziert.",
            "Clicking one of the 32 swatches opens the color dialog. Colors are reduced to 15 bits."),
        ("Verlauf", "Gradient"),
        ("Verteilt die Farben dazwischen gleichmäßig zwischen Farbe 1 und Farbe 32.", "Distributes the colors in between evenly from color 1 to color 32."),
        ("Farben von Hue kopieren", "Copy colors from Hue"),
        ("Übernimmt alle 32 Farben eines anderen Hues, Name und Tabellenwerte bleiben.", "Takes over all 32 colors of another Hue; name and table values stay."),
        ("<p>Alle Bodies mit ihren Quellen: anim.mul bis anim6.mul, bodyconv.def, body.def und UOP.</p>",
            "<p>All bodies with their sources: anim.mul to anim6.mul, bodyconv.def, body.def and UOP.</p>"),
        ("Quellen", "Sources"),
        ("Mul (A1 bis A6) oder UOP. Eine Zeile kann mehrere Quellen haben.", "Mul (A1 to A6) or UOP. A row can have several sources."),
        ("Chardef ohne Animation", "Chardef without animation"),
        ("Filter für Sphere-Chardefs (nur mit Skriptordner), deren Body keine Animationsdaten hat und die deshalb unsichtbar wären.",
            "Filter for Sphere chardefs (only with a script folder) whose body has no animation data and which would therefore be invisible."),
        ("Vorschau", "Preview"),
        ("Quelle, Aktion und Richtung oben in der Vorschau wählen. Zoom und Hintergrund sind einstellbar.",
            "Choose source, action and direction at the top of the preview. Zoom and background are adjustable."),
        ("<p>Animations-IDs, die Items in der Tiledata benutzen, samt Paperdoll-Gumps und den Items, die sie verwenden.",
            "<p>Animation IDs that items use in the Tiledata, along with Paperdoll Gumps and the items that use them."),
        ("<p>Jede Animationsdatei einzeln, ohne body.def und bodyconv.def, dazu die UOP-Dateien. Nützlich, um zu sehen, was wirklich in einer Datei steht.",
            "<p>Each animation file individually, without body.def and bodyconv.def, plus the UOP files. Useful to see what is really inside a file."),
        ("<p>Nur nutzbar, wenn im Zahnrad-Menü ein Sphere-Skriptordner angegeben ist (Sphere-Skriptformat mit <code>[ITEMDEF ...]</code>-Abschnitten). Jede Definition steht als eine Zeile: Defname, Kopf, aufgelöste Item-ID, Name im Skript, Name in der Tiledata, Kategorie, Datei und Zeile. Das ist der Rückweg zu den Items: Du siehst, welche Definitionen es gibt und wo in den Tiledata oder der Art etwas fehlt.</p>",
            "<p>Only usable if a Sphere script folder is specified in the gear menu (Sphere script format with <code>[ITEMDEF ...]</code> sections). Each definition is one row: defname, header, resolved item ID, name in the script, name in the Tiledata, category, file and line. This is the way back to the items: you can see which definitions exist and where something is missing in the Tiledata or Art.</p>"),
        ("Problem", "Problem"),
        ("Zeigt 'Tiledata ohne Name', 'Art fehlt', 'ID nicht aufgelöst' (die ID= der Definition verweist auf etwas, das UOTinker nicht auflösen konnte) und 'ID außerhalb der Tiledata'. Der Filter 'Problem' grenzt danach ein.",
            "Shows 'Tiledata without name', 'Art missing', 'ID not resolved' (the ID= of the definition points to something UOTinker could not resolve) and 'ID outside the Tiledata'. The 'Problem' filter narrows it down accordingly."),
        ("Skript öffnen", "Open script"),
        ("Öffnet die Datei an der Zeile der Definition (VS Code, sonst Notepad++, sonst Standardprogramm).",
            "Opens the file at the line of the definition (VS Code, otherwise Notepad++, otherwise the default program)."),
        ("Im Tiledata zeigen / Bei Items (Art) zeigen", "Show in Tiledata / Show in Items (Art)"),
        ("Wechselt auf die jeweilige Seite und springt zum Eintrag dieser Item-ID. Filter und Suche der Zielseite werden dafür zurückgesetzt.",
            "Switches to the respective page and jumps to the entry of this item ID. The filters and search of the target page are reset for this."),
        ("Die Skripte werden nur gelesen, UOTinker ändert sie nie. Die Liste entsteht beim Laden; nach Änderungen an den Skripten mit 'Neu laden' aktualisieren. Der Sprung Item -> ITEMDEF sitzt im Tiledata-Editor ('ITEMDEF ...' und 'in der ITEMDEF-Liste zeigen').",
            "The scripts are only read, UOTinker never modifies them. The list is built on load; after changing the scripts, refresh with 'Reload'. The jump from item to ITEMDEF is in the Tiledata editor ('ITEMDEF ...' and 'show in ITEMDEF list')."),
        ("<p>Skills aus skills.idx/skills.mul mit Name und Aktiv-Kennzeichen.</p>", "<p>Skills from skills.idx/skills.mul with name and active flag.</p>"),
        ("Skill vorhanden", "Skill exists"),
        ("Belegt einen freien Slot oder gibt einen Slot wieder frei.", "Occupies a free slot or frees a slot again."),
        ("Skill-Button", "Skill button"),
        ("Ob der Skill im Skillfenster einen Knopf hat.", "Whether the skill has a button in the skill window."),
        ("Schreibt skills.mul und skills.idx neu (Reihenfolge der Daten in der mul-Datei ändert sich, die Zuordnung nicht). Zuvor werden beide Dateien unter %APPDATA%\\UOTinker\\backups gesichert.",
            "Rewrites skills.mul and skills.idx (the order of the data in the mul file changes, the mapping does not). Beforehand, both files are backed up to %APPDATA%\\UOTinker\\backups."),
        ("<p>Alle Texte der Cliloc-Dateien je Sprache (komprimierte Dateien werden entpackt). Suche nach Nummer oder Text.</p>",
            "<p>All texts of the Cliloc files per language (compressed files are unpacked). Search by number or text.</p>"),
        ("Text bearbeiten", "Edit text"),
        ("Das Feld rechts ändert den Text des gewählten Eintrags. Zeilenumbrüche gibt es in Cliloc-Texten nicht, sie werden zu Leerzeichen.",
            "The field on the right changes the text of the selected entry. Cliloc texts have no line breaks; they are turned into spaces."),
        ("Neuer Eintrag", "New entry"),
        ("Legt eine neue Nummer mit Text an (am Dateiende).", "Creates a new number with text (at the end of the file)."),
        ("Komprimierte (BWT) Dateien lassen sich anzeigen, aber nicht schreiben.", "Compressed (BWT) files can be displayed but not written."),
        ("<p>Die Tiledata (tiledata.mul) legt für jedes Land- und Item-Tile fest, was es im Spiel ist: Name, Flags, Gewicht, Höhe, Layer, Menge, AnimID, Hue und Licht. Das Item-Bild steht in art.mul, seine Eigenschaften hier. Der Client liest die Datei, Server-Emulatoren meist ebenfalls.</p>",
            "<p>The Tiledata (tiledata.mul) defines for every land and item tile what it is in the game: name, flags, weight, height, layer, quantity, AnimID, Hue and light. The item image is in art.mul, its properties are here. The client reads the file, and server emulators usually do too.</p>"),
        ("Standard ist das Raster mit der Grafik jedes Eintrags. Die Beschriftung 'I' steht für Item, 'L' für Land.",
            "The default is the grid with the graphic of each entry. The label 'I' stands for item, 'L' for land."),
        ("Zeigt automatisch erkannte Lücken. Mit dem Filter 'Problem' wählst du einzelne Arten aus. Die Arten stehen unter {0}.",
            "Shows automatically detected gaps. With the 'Problem' filter you pick individual types. The types are listed under {0}."),
        ("Problemarten", "Problem types"),
        ("Typ, Eintrag (leer oder gefüllt), Problem, jedes der 32 Flags einzeln, Art vorhanden und Sphere-ITEMDEF vorhanden.",
            "Type, entry (empty or filled), problem, each of the 32 flags individually, Art present and Sphere ITEMDEF present."),
        ("Ändern", "Editing"),
        ("Wähle einen Eintrag und ändere die Werte rechts. Siehe {0}.", "Select an entry and change the values on the right. See {0}."),
        ("Art ohne Tiledata", "Art without Tiledata"),
        ("Es gibt eine Grafik, aber weder Name noch Flags.", "There is a graphic, but neither name nor flags."),
        ("Tiledata ohne Art", "Tiledata without Art"),
        ("Name oder Flags sind gepflegt, aber es gibt keine Grafik.", "Name or flags are maintained, but there is no graphic."),
        ("Wearable ohne AnimID", "Wearable without AnimID"),
        ("Das Item hat das Wearable-Flag, aber keine AnimID und wird am Körper nicht gezeichnet.",
            "The item has the Wearable flag but no AnimID and is not drawn on the body."),
        ("AnimID ohne Animation", "AnimID without animation"),
        ("Die AnimID zeigt auf eine Body-ID, zu der es in keiner Quelle Frames gibt.", "The AnimID points to a body ID that has no frames in any source."),
        ("Paperdoll-Gump fehlt", "Paperdoll gump missing"),
        ("Ein tragbares Item mit AnimID hat weder männlichen (50000 + AnimID) noch weiblichen Gump (60000 + AnimID).",
            "A wearable item with an AnimID has neither a male (50000 + AnimID) nor a female Gump (60000 + AnimID)."),
        ("Wearable ohne Layer", "Wearable without Layer"),
        ("Das Wearable-Flag ist gesetzt, aber der Layer ist 0.", "The Wearable flag is set, but the Layer is 0."),
        ("ITEMDEF ohne Tiledata-Name", "ITEMDEF without Tiledata name"),
        ("Die Sphere-Skripte (falls angegeben) definieren das Item, die Tiledata hat aber keinen Namen dafür.",
            "The Sphere scripts (if specified) define the item, but the Tiledata has no name for it."),
        ("Nicht jedes Problem ist ein Fehler. Offizielle Bereiche sind teils absichtlich leer. Die Liste soll zeigen, wo man hinschauen muss.",
            "Not every problem is an error. Official ranges are partly empty on purpose. The list is meant to show where to look."),
        ("<p>Rechts neben der Liste steht ein Formular zum gewählten Eintrag. Änderungen gelten sofort im Programm, sind aber erst nach dem Speichern in der Datei.</p>",
            "<p>To the right of the list is a form for the selected entry. Changes apply immediately in the program but are only in the file after saving.</p>"),
        ("Höchstens 20 Zeichen, Latin-1.", "At most 20 characters, Latin-1."),
        ("Gewicht", "Weight"),
        ("0 bis 255. 255 bedeutet 'nicht aufhebbar'.", "0 to 255. 255 means 'cannot be picked up'."),
        ("Hoehe", "Height"),
        ("Höhe des Tiles, bestimmt Laufbarkeit und Stapeln.", "Height of the tile; determines walkability and stacking."),
        ("Layer", "Layer"),
        ("Körperslot bei tragbaren Items.", "Body slot for wearable items."),
        ("Menge", "Quantity"),
        ("Stapelmenge.", "Stack quantity."),
        ("Body-ID der Animation beim Tragen; zugleich Basis der Paperdoll-Gumps.", "Body ID of the animation when worn; also the basis of the Paperdoll Gumps."),
        ("Hue", "Hue"),
        ("Standardfarbe.", "Default color."),
        ("Licht", "Light"),
        ("Lichtart bei Lichtquellen.", "Light type for light sources."),
        ("TexID", "TexID"),
        ("Nur bei Land: Textur der Kachel.", "Land only: texture of the tile."),
        ("Flags", "Flags"),
        ("Die 32 unteren Flag-Bits als Kästchen. Die oberen 32 Bits der 64-Bit-Flags bleiben unverändert erhalten.",
            "The lower 32 flag bits as checkboxes. The upper 32 bits of the 64-bit flags are preserved unchanged."),
        ("Schreibt alle geänderten Einträge in tiledata.mul. Zuvor wird die vorherige Datei unter %APPDATA%\\UOTinker\\backups gesichert. Die Zahl in Klammern ist die Menge der geänderten Einträge.",
            "Writes all changed entries to tiledata.mul. Beforehand, the previous file is backed up to %APPDATA%\\UOTinker\\backups. The number in parentheses is the count of changed entries."),
        ("Der Button ist bei aktivem Schreibschutz gesperrt. Geänderte Einträge sind in der Liste mit * markiert.",
            "The button is disabled while write protection is on. Changed entries are marked with * in the list."),
        ("Werte kopieren", "Copy values"),
        ("Übernimmt Werte eines anderen Eintrags (ID dezimal oder 0x hex). Im Dialog wählst du, welche Felder kopiert werden: Name, Flags, Gewicht, Höhe, Layer, Menge, AnimID, Hue, Licht (bei Land: Name, Flags, TexID). Vorbelegt sind alles außer Name, AnimID und Hue. Items kopieren nur von Items, Land nur von Land.",
            "Takes over values from another entry (ID decimal or 0x hex). In the dialog you choose which fields are copied: name, flags, weight, height, layer, quantity, AnimID, Hue, light (for land: name, flags, TexID). Everything except name, AnimID and Hue is preselected. Items copy only from items, land only from land."),
        ("Neues Item anlegen", "Create new item"),
        ("Belegt einen freien Slot der Tiledata. Mit 'Nächster mit Art, ohne Tiledata' findest du Grafiken, die noch keine Eigenschaften haben; 'Nächster ganz freier' sucht einen Slot ohne Grafik und ohne Tiledata. Optional liefert eine Vorlage alle Werte außer dem Namen. Optional wählst du ein Bild; es wird im selben Schritt als Item-Art für diese ID vorgemerkt (Format und Hinweise siehe Item-Art bearbeiten). Mit 'Sofort speichern' werden Tiledata und Art gleich geschrieben, jeweils mit Sicherung; ohne bleiben beide als ungespeicherte Änderung stehen. Danach springt die Liste zum neuen Eintrag.",
            "Occupies a free Tiledata slot. 'Next with Art, without Tiledata' finds graphics that have no properties yet; 'Next completely free' looks for a slot without graphic and without Tiledata. Optionally a template supplies all values except the name. Optionally you pick an image; it is queued as item Art for this ID in the same step (for format and notes see Editing item Art). With 'Save immediately', Tiledata and Art are written right away, each with a backup; without it, both remain as unsaved changes. Afterwards the list jumps to the new entry."),
        ("Ohne Bild meldet die Problemliste 'Tiledata ohne Art'. Ein belegter Slot (Tiledata oder Art) wird nur nach Rückfrage überschrieben. Ist das Bild nicht verwendbar, wird nichts geändert.",
            "Without an image, the problem list reports 'Tiledata without Art'. An occupied slot (Tiledata or Art) is only overwritten after confirmation. If the image cannot be used, nothing is changed."),
        ("ITEMDEF ...", "ITEMDEF ..."),
        ("Nur bei Items. Öffnet ein Menü mit allen Sphere-Definitionen, die zu dieser ID gehören (Defname, Datei und Zeile). Ein Klick öffnet die Skriptdatei an der Zeile, bevorzugt in VS Code, sonst in Notepad++, sonst im Standardprogramm (dort ohne Zeilensprung). Gehört eine Definition zu einer anderen Item-ID (z. B. ein Alias mit ID= auf diese Grafik), gibt es zusätzlich 'zu Item ... springen', das in der Liste zu dem Item wechselt. Gibt es keine Definition, steht das im Menü. UOTinker ändert die Skripte nie selbst.",
            "Items only. Opens a menu with all Sphere definitions belonging to this ID (defname, file and line). A click opens the script file at that line, preferably in VS Code, otherwise in Notepad++, otherwise in the default program (without jumping to the line). If a definition belongs to a different item ID (e.g. an alias with ID= pointing to this graphic), there is an additional 'jump to item ...' entry that switches to that item in the list. If there is no definition, the menu says so. UOTinker never modifies the scripts itself."),
        ("Problemregeln ...", "Problem rules ..."),
        ("Legt fest, welche Prüfungen als Problem gemeldet werden: Art ohne Tiledata, Tiledata ohne Art, Wearable ohne AnimID, AnimID ohne Animation, Paperdoll-Gump fehlt, Wearable ohne Layer und ITEMDEF ohne Tiledata-Name. Abgewählte Prüfungen verschwinden aus der Problem-Spalte, den Filtern, der Karte 'Items mit Lücken' und den Schnellaktionen. Das ist sinnvoll, wenn eine Prüfung bei dir bewusst nicht zutrifft, etwa 'AnimID ohne Animation' bei Items, die nur teilweise Animationen haben. Die Auswahl wird gespeichert und gilt für alle Datenordner; die Daten selbst ändern sich nicht.",
            "Defines which checks are reported as problems: Art without Tiledata, Tiledata without Art, Wearable without AnimID, AnimID without animation, Paperdoll Gump missing, Wearable without Layer and ITEMDEF without Tiledata name. Deselected checks disappear from the Problem column, the filters, the 'Items with gaps' card and the quick actions. This makes sense if a check deliberately does not apply to you, for example 'AnimID without animation' for items that only have partial animations. The selection is saved and applies to all data folders; the data itself does not change."),
        ("Eintrag zurücksetzen", "Reset entry"),
        ("Stellt den gewählten Eintrag auf den Stand der Datei zurück.", "Restores the selected entry to the state of the file."),
        ("Alle verwerfen", "Discard all"),
        ("Verwirft alle ungespeicherten Änderungen.", "Discards all unsaved changes."),
        ("Andere Kopien der Datei (zum Beispiel beim Server oder bei den Spielern) werden nicht automatisch angepasst; sie müssen nach dem Speichern wie gewohnt verteilt werden. Beim Beenden oder Neuladen fragt das Programm, wenn ungespeicherte Änderungen vorhanden sind.",
            "Other copies of the file (for example on the server or with the players) are not updated automatically; after saving they must be distributed as usual. When exiting or reloading, the program asks if there are unsaved changes."),
    };
}
