namespace UOTinker;

public static class LocEn2
{
    public static readonly (string de, string en)[] Pairs =
    {
        ("Status", "Status"),
        ("Alle", "All"),
        ("Belegt", "Used"),
        ("Frei", "Free"),
        ("Groesse", "Size"),
        ("Tiledata-Name", "Tiledata name"),
        ("ausserhalb", "out of range"),
        ("frei", "free"),
        ("belegt", "in use"),
        ("Mit Name", "With name"),
        ("Ohne Name", "Without name"),
        ("Mit ITEMDEF", "With ITEMDEF"),
        ("Ohne ITEMDEF", "Without ITEMDEF"),
        ("Mit AnimID", "With AnimID"),
        ("Ohne", "Without"),
        ("{0} Slots, {1} belegt, {2} frei", "{0} slots, {1} used, {2} free"),
        ("Item-Art {0} ({1})  -  artidx-Index {2}", "Item art {0} ({1})  -  artidx index {2}"),
        ("Tiledata-Name: {0}", "Tiledata name: {0}"),
        ("Gewicht {0}, Hoehe {1}, Layer {2}, Menge {3}, AnimID {4}, Hue {5}, Licht {6}", "Weight {0}, Height {1}, Layer {2}, Quantity {3}, AnimID {4}, Hue {5}, Light {6}"),
        ("Textur", "Texture"),
        ("Mit TexID", "With TexID"),
        ("Land-Tile {0} ({1})\n", "Land tile {0} ({1})\n"),
        ("Bedeutung", "Meaning"),
        ("Paperdoll weiblich, AnimID {0}", "Paperdoll female, AnimID {0}"),
        ("Paperdoll maennlich, AnimID {0}", "Paperdoll male, AnimID {0}"),
        ("Bereich", "Range"),
        ("50000-59999 (Paperdoll m)", "50000-59999 (Paperdoll male)"),
        (">= 60000 (Paperdoll w)", ">= 60000 (Paperdoll female)"),
        ("Art ohne Tiledata", "Art without Tiledata"),
        ("Tiledata ohne Art", "Tiledata without Art"),
        ("Wearable ohne AnimID", "Wearable without AnimID"),
        ("AnimID ohne Animation", "AnimID without animation"),
        ("Paperdoll-Gump fehlt", "Paperdoll gump missing"),
        ("Wearable ohne Layer", "Wearable without Layer"),
        ("ITEMDEF ohne Tiledata-Name", "ITEMDEF without Tiledata name"),
        ("Typ", "Type"),
        ("Problem", "Problem"),
        ("Gew.", "Wt."),
        ("Hoehe", "Height"),
        ("Menge", "Qty"),
        ("Licht", "Light"),
        ("ja", "yes"),
        ("nein", "no"),
        ("Eintrag", "Entry"),
        ("Leer (kein Name/Flags)", "Empty (no name/flags)"),
        ("Gefuellt", "Filled"),
        ("Irgendein Problem", "Any problem"),
        ("Kein Problem", "No problem"),
        ("Mit Art", "With Art"),
        ("Ohne Art", "Without Art"),
        ("{0} Land + {1} Items, Format {2}  |  {3}", "{0} Land + {1} Items, format {2}  |  {3}"),
        ("alt (32-Bit)", "old (32-bit)"),
        ("neu (64-Bit)", "new (64-bit)"),
        ("(leer)", "(empty)"),
        ("Gewicht: {0}{1}", "Weight:  {0}{1}"),
        (" (nicht aufhebbar)", " (cannot be picked up)"),
        ("Hoehe:   {0}", "Height:  {0}"),
        ("Menge:   {0}", "Count:   {0}"),
        ("Licht:   {0}", "Light:   {0}"),
        ("Paperdoll m ({0})", "Paperdoll male ({0})"),
        ("Paperdoll w ({0})", "Paperdoll female ({0})"),
        ("PROBLEME:", "PROBLEMS:"),
        ("Farbe (16 Bit)", "Color (16-bit)"),
        ("schwarz/leer", "black/empty"),
        ("Farbe", "Color"),
        ("Schwarz/leer", "Black/empty"),
        ("{0} Eintraege", "{0} entries"),
        ("Radarfarbe {0} {1} ({2}): 0x{3:X4}", "Radar color {0} {1} ({2}): 0x{3:X4}"),
        ("TabelleStart", "TableStart"),
        ("TabelleEnde", "TableEnd"),
        ("Farbe 1", "Color 1"),
        ("Farbe 32", "Color 32"),
        ("Leer", "Empty"),
        ("{0} Hues ({1} Gruppen), {2} leer", "{0} hues ({1} groups), {2} empty"),
        ("Hue {0} ({1}): \"{2}\"\nTabelle {3} - {4}\n", "Hue {0} ({1}): \"{2}\"\nTable {3} - {4}\n"),
        ("{0} Slots, {1} belegt", "{0} slots, {1} used"),
        ("Skill {0} ({1}): {2}\nSkill-Button: {3}", "Skill {0} ({1}): {2}\nSkill button: {3}"),
        ("Nummer", "Number"),
        ("Fehler: ", "Error: "),
        ("{0} Eintraege{1}", "{0} entries{1}"),
        (" (BWT-komprimiert)", " (BWT-compressed)"),
        ("Quellen", "Sources"),
        ("Aktionen", "Actions"),
        ("Beispiele (Tiledata)", "Examples (Tiledata)"),
        ("FEHLT", "MISSING"),
        ("Frei/fehlt", "Free/missing"),
        ("Nur FEHLT (Chardef ohne Animation)", "Only MISSING (Chardef without animation)"),
        ("Quelle", "Source"),
        ("Nur Mul", "Mul only"),
        ("Nur UOP", "UOP only"),
        ("Mit Chardef", "With Chardef"),
        ("Ohne Chardef", "Without Chardef"),
        ("Hoch (<200)", "High (<200)"),
        ("Niedrig (200-399)", "Low (200-399)"),
        ("Menschlich (400+)", "Human (400+)"),
        ("Nur Item-AnimIDs", "Item AnimIDs only"),
        ("Ohne Item-AnimIDs", "Without item AnimIDs"),
        ("{0} Zeilen, {1} mit Animation, {2} Chardefs ohne Animation", "{0} rows, {1} with animation, {2} Chardefs without animation"),
        ("Keine Animationsdaten in anim.mul, anim2-6.mul oder UOP.", "No animation data in anim.mul, anim2-6.mul or UOP."),
        ("Item-AnimID, benutzt von {0} Items, z.B.: {1}", "Item AnimID, used by {0} items, e.g.: {1}"),
        ("Paperdoll m (Gump {0})", "Paperdoll male (Gump {0})"),
        ("Paperdoll w (Gump {0})", "Paperdoll female (Gump {0})"),
        ("Aktions-Nummern", "Action numbers"),
        ("Sphere (gleiche Nr. als Body)", "Sphere (same no. as body)"),
        ("{0} Slots, {1} belegt (Datei-Index; bodyconv.def/body.def werden hier NICHT angewendet)", "{0} slots, {1} used (file index; bodyconv.def/body.def are NOT applied here)"),
        ("Slot ist frei.", "Slot is free."),
        ("{0} Aktionen", "{0} actions"),
        ("Keine Eintraege in dieser Auswahl.", "No entries in this selection."),
        ("kein\nBild", "no\nimage"),
        ("Abspielen", "Play"),
        ("Standard", "Default"),
        ("Schwarz", "Black"),
        ("Weiss", "White"),
        ("Hellgrau", "Light gray"),
        ("Aktion", "Action"),
        ("Richtung", "Direction"),
        ("Hintergrund", "Background"),
        ("Aktion {0}", "Action {0}"),
        ("\r\n[{0}, Aktion {1}, Richtung {2}] keine Frames. {3}", "\r\n[{0}, action {1}, direction {2}] no frames. {3}"),
        ("Suche:", "Search:"),
        ("Gehe zu ID:", "Go to ID:"),
        ("CSV exportieren", "Export CSV"),
        ("Raster", "Grid"),
        ("Liste", "List"),
        ("Ansicht:", "View:"),
        ("Zelle:", "Cell:"),
        ("{0} von {1} angezeigt", "{0} of {1} shown"),
        ("Fehler bei der Vorschau: ", "Preview error: "),
        ("ID {0} in der aktuellen Auswahl nicht gefunden", "ID {0} not found in the current selection"),
        ("Angezeigte Liste als CSV speichern", "Save displayed list as CSV"),
        ("{0} Zeilen nach {1} exportiert", "{0} rows exported to {1}"),
        ("Export fehlgeschlagen: ", "Export failed: "),
    };
}
