namespace UOTinker;

public static class LocEn4
{
    public static readonly (string de, string en)[] Pairs =
    {
        ("Defname", "Defname"),
        ("Kopf", "Header"),
        ("Item-ID", "Item ID"),
        ("Hex", "Hex"),
        ("Name (Sphere)", "Name (Sphere)"),
        ("Tiledata-Name", "Tiledata name"),
        ("Kategorie", "Category"),
        ("Datei", "File"),
        ("Zeile", "Line"),
        ("Problem", "Problem"),
        ("Alle", "All"),
        ("Irgendein Problem", "Any problem"),
        ("Ohne Problem", "No problem"),
        ("Tiledata ohne Name", "Tiledata without name"),
        ("Art fehlt", "Art missing"),
        ("ID nicht aufgelöst", "ID not resolved"),
        ("Item-ID nicht aufgelöst", "Item ID not resolved"),
        ("ID außerhalb der Tiledata", "ID outside the tiledata"),
        ("ITEMDEF konnte nicht geöffnet werden: ", "Could not open ITEMDEF: "),
        ("{0:N0} ITEMDEFs in {1} Skriptdateien", "{0:N0} ITEMDEFs in {1} script files"),
        ("Kopf:      [ITEMDEF {0}]", "Header:    [ITEMDEF {0}]"),
        ("Datei:     {0}:{1}", "File:      {0}:{1}"),
        ("Name:      {0}", "Name:      {0}"),
        ("Kategorie: {0}", "Category:  {0}"),
        ("Item-ID:   {0} ({1})", "Item ID:   {0} ({1})"),
        ("Tiledata:  {0}", "Tiledata:  {0}"),
        ("(Name leer)", "(name empty)"),
        ("Weitere ITEMDEFs mit dieser ID: {0}", "Other ITEMDEFs with this ID: {0}"),
        ("PROBLEME:", "PROBLEMS:"),
        ("Skript öffnen", "Open script"),
        ("{0}:{1} geöffnet.", "{0}:{1} opened."),
        ("Im Tiledata zeigen", "Show in Tiledata"),
        ("Bei Items (Art) zeigen", "Show in Items (Art)"),

        ("Aus Bild importieren ...", "Import from image ..."),
        ("Als PNG exportieren ...", "Export as PNG ..."),
        ("Slot leeren", "Clear slot"),
        ("Eintrag zurücksetzen", "Reset entry"),
        ("Alle verwerfen", "Discard all"),
        ("Speichern", "Save"),
        ("{0} {1} ({2}) bearbeiten", "Edit {0} {1} ({2})"),
        ("{0} ungespeicherte Änderungen verwerfen?", "Discard {0} unsaved changes?"),
        ("Item-Art", "Item art"),
        ("Land-Kachel", "Land tile"),
        ("Gump", "Gump"),
        ("Grafik vorhanden: {0} x {1} Pixel{2}", "Graphic present: {0} x {1} pixels{2}"),
        ("  (geändert, noch nicht gespeichert)", "  (changed, not saved yet)"),
        ("Slot wird beim Speichern geleert.", "Slot will be cleared on save."),
        ("Slot ist frei (keine Grafik).", "Slot is free (no graphic)."),
        ("Land-Kacheln sind immer 44 x 44 Pixel; nur die Raute in der Mitte wird gespeichert.", "Land tiles are always 44 x 44 pixels; only the diamond in the middle is saved."),
        ("Gumps speichern ({0})", "Save Gumps ({0})"),
        ("Art speichern ({0})", "Save Art ({0})"),
        ("Schreibschutz aktiv: Zahnrad unten links, 'Schreibschutz' ausschalten.", "Write protection is on: gear icon at the bottom left, turn off 'Write protection'."),
        ("Die Tiledata dieses Items ist noch leer. Im Tab Tiledata ergänzen.", "The tiledata of this item is still empty. Fill it in on the Tiledata tab."),
        ("Bild für {0} wählen", "Choose image for {0}"),
        ("Bilder (*.png;*.bmp;*.gif;*.jpg)|*.png;*.bmp;*.gif;*.jpg|Alle Dateien|*.*", "Images (*.png;*.bmp;*.gif;*.jpg)|*.png;*.bmp;*.gif;*.jpg|All files|*.*"),
        ("Bild konnte nicht gelesen werden: ", "Could not read image: "),
        ("Nicht importiert: ", "Not imported: "),
        ("Slot {0} ({1}) enthält bereits eine Grafik. Ersetzen?", "Slot {0} ({1}) already contains a graphic. Replace it?"),
        ("Export nicht möglich: ", "Export not possible: "),
        ("Als PNG speichern", "Save as PNG"),
        ("Exportiert nach ", "Exported to "),
        ("Grafik in Slot {0} ({1}) beim Speichern entfernen?", "Remove the graphic in slot {0} ({1}) on save?"),
        ("Speichern fehlgeschlagen: ", "Save failed: "),
        ("gumpart.mul angehängt und gumpidx.mul", "gumpart.mul (appended) and gumpidx.mul"),
        ("art.mul angehängt und artidx.mul", "art.mul (appended) and artidx.mul"),
        ("{0} Grafik(en) in {1} aktualisiert. Sicherung des Index: {2}", "{0} graphic(s) updated in {1}. Index backup: {2}"),

        ("Werte kopieren ...", "Copy values ..."),
        ("Neues Item anlegen ...", "Create new item ..."),
        ("Problemregeln ...", "Problem rules ..."),
        ("Land-Tile {0} ({1}) bearbeiten", "Edit land tile {0} ({1})"),
        ("Item {0} ({1}) bearbeiten", "Edit item {0} ({1})"),
        ("Name", "Name"),
        ("TexID", "TexID"),
        ("Gewicht", "Weight"),
        ("Hoehe", "Height"),
        ("Layer", "Layer"),
        ("Menge", "Quantity"),
        ("AnimID", "AnimID"),
        ("Hue", "Hue"),
        ("Licht", "Light"),
        ("Flags", "Flags"),
        ("Speichern ({0})", "Save ({0})"),
        ("{0} Änderung(en) noch nicht gespeichert.", "{0} change(s) not saved yet."),
        ("Keine ungespeicherten Änderungen.", "No unsaved changes."),
        ("ID außerhalb des Bereichs", "ID out of range"),
        ("(ohne Name)", "(no name)"),
        ("leer", "empty"),
        ("belegt", "in use"),
        ("vorhanden", "present"),
        ("fehlt", "missing"),
        ("{0}  |  Tiledata {1}  |  Art {2}", "{0}  |  Tiledata {1}  |  Art {2}"),
        ("Problemregeln", "Problem rules"),
        ("Welche Prüfungen sollen als Problem gemeldet werden?", "Which checks should be reported as problems?"),
        ("Übernehmen", "Apply"),
        ("Abbrechen", "Cancel"),
        ("Alle Prüfungen aktiv.", "All checks enabled."),
        ("{0} von {1} Prüfungen aktiv.", "{0} of {1} checks enabled."),
        ("{0}  ({1}:{2}) öffnen", "Open {0}  ({1}:{2})"),
        ("   → in der ITEMDEF-Liste zeigen", "   → show in the ITEMDEF list"),
        ("   → zu Item {0} ({1}) springen", "   → jump to item {0} ({1})"),
        ("Kein ITEMDEF für dieses Item gefunden", "No ITEMDEF found for this item"),
        ("Werte kopieren", "Copy values"),
        ("Land-Tile (ID/0x)", "Land tile (ID/0x)"),
        ("Quell-Item (ID/0x)", "Source item (ID/0x)"),
        ("Höhe", "Height"),
        ("Kopieren", "Copy"),
        ("Bitte eine gültige, andere ID eingeben.", "Please enter a valid ID different from this one."),
        ("Neues Item anlegen", "Create new item"),
        ("Nächster mit Art, ohne Tiledata", "Next with art, without tiledata"),
        ("Nächster ganz freier", "Next completely free"),
        ("Neue Item-ID (ID/0x)", "New item ID (ID/0x)"),
        ("Vorlage (optional)", "Template (optional)"),
        ("Bild wählen ...", "Choose image ..."),
        ("Sofort speichern (Tiledata und Art)", "Save immediately (tiledata and art)"),
        ("Bild (optional)", "Image (optional)"),
        ("Die Vorlage liefert Flags, Gewicht, Höhe, Layer, Menge, AnimID, Hue und Licht. Mit einem Bild wird die Grafik im selben Schritt in art.mul vorgemerkt; ohne Bild meldet die Problemliste 'Tiledata ohne Art'. Ohne 'Sofort speichern' bleibt beides als ungespeicherte Änderung stehen.", "The template provides flags, weight, height, layer, quantity, AnimID, hue and light. With an image, the graphic is queued for art.mul in the same step; without one, the problem list reports 'Tiledata without art'. Without 'Save immediately', both stay as unsaved changes."),
        ("Bild für die Item-Art wählen", "Choose image for the item art"),
        ("Anlegen", "Create"),
        ("Bitte eine gültige ID eingeben.", "Please enter a valid ID."),
        ("Ungültige Vorlage.", "Invalid template."),
        ("Die Art kann nicht geschrieben werden, der Schreibschutz ist aktiv.", "The art cannot be written because write protection is on."),
        ("Bild nicht verwendbar: ", "Image not usable: "),
        ("Item {0} (0x{1:X}) ist in der Tiledata bereits belegt ({2}). Überschreiben?", "Item {0} (0x{1:X}) is already in use in the tiledata ({2}). Overwrite?"),
        ("Slot {0} (0x{1:X}) enthält in art.mul bereits eine Grafik. Ersetzen?", "Slot {0} (0x{1:X}) already contains a graphic in art.mul. Replace it?"),
        ("Teilweise nicht gespeichert (Änderungen bleiben im Programm erhalten):\n{0}{1}", "Partly not saved (changes are kept in the program):\n{0}{1}"),
        ("Tiledata und Art gespeichert. Sicherungen liegen unter %APPDATA%\\UOTinker\\backups.", "Tiledata and art saved. Backups are in %APPDATA%\\UOTinker\\backups."),
        ("Tiledata gespeichert. Sicherungen liegen unter %APPDATA%\\UOTinker\\backups.", "Tiledata saved. Backups are in %APPDATA%\\UOTinker\\backups."),
        ("{0} Änderung(en) in tiledata.mul gespeichert. Sicherung: {1}\nDie Datei muss zusätzlich dort verteilt werden, wo sie gebraucht wird (Client, Server).", "{0} change(s) saved to tiledata.mul. Backup: {1}\nThe file must also be distributed wherever it is needed (client, server)."),

        ("{0} Änderung(en) in {1} gespeichert. Sicherung: {2}\nDie Datei muss zusätzlich dort verteilt werden, wo sie gebraucht wird (Client, Server).", "{0} change(s) saved to {1}. Backup: {2}\nThe file must also be distributed wherever it is needed (client, server)."),
        ("Farbe wählen ...", "Choose color ..."),
        ("Aus der Grafik berechnen", "Calculate from graphic"),
        ("Fehlende Item-Farben füllen ...", "Fill missing item colors ..."),
        ("radarcol.mul fehlt im Datenordner.", "radarcol.mul is missing in the data folder."),
        ("Radarfarbe {0} {1} ({2}) bearbeiten", "Edit radar color {0} {1} ({2})"),
        ("Farbe (15 Bit, hex)", "Color (15-bit, hex)"),
        ("Für diesen Eintrag gibt es keine Grafik.", "This entry has no graphic."),
        ("Alle Items mit Grafik haben schon eine Radarfarbe.", "All items with a graphic already have a radar color."),
        ("{0} Items haben eine Grafik, aber die Radarfarbe 0. Farben aus den Grafiken berechnen und als Änderung vormerken?", "{0} items have a graphic but radar color 0. Calculate colors from the graphics and queue them as a change?"),
        ("hues.mul fehlt im Datenordner.", "hues.mul is missing in the data folder."),
        ("Hue {0} ({1}) bearbeiten", "Edit hue {0} ({1})"),
        ("Tabelle von", "Table from"),
        ("bis", "to"),
        ("Verlauf zwischen Farbe 1 und 32", "Gradient between color 1 and 32"),
        ("Farben von Hue kopieren", "Copy colors from Hue"),
        ("Skill vorhanden", "Skill exists"),
        ("Skill-Button im Fenster", "Skill button in window"),
        ("skills.mul und skills.idx", "skills.mul and skills.idx"),
        ("skills.idx fehlt im Datenordner.", "skills.idx is missing in the data folder."),
        ("Skill {0} ({1}) bearbeiten", "Edit skill {0} ({1})"),
        ("Neuer Eintrag ...", "New entry ..."),
        ("Cliloc {0} ({1}) bearbeiten", "Edit cliloc {0} ({1})"),
        ("Neuer Cliloc-Eintrag", "New cliloc entry"),
        ("Nummer (dezimal oder 0x)", "Number (decimal or 0x)"),
        ("Text", "Text"),
        ("Bitte eine gültige Nummer eingeben.", "Please enter a valid number."),
        ("Diese Nummer gibt es schon.", "This number already exists."),
    };
}
